import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNavBar from './components/Navigation/MainNavBar'
import AuthContext from './context/auth-context'
import Providers from './context/providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} prose`}>
        <Providers>
          <MainNavBar/>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <div className="z-10 max-w-5xl w-full items-center justify-between font-mono lg:flex">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
