import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNavBar from './components/Navigation/MainNavBar'
import Providers from './context/providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="acid">
      <body className={`${inter.className} prose m-auto`}>
        <Providers>
          <MainNavBar />
          <main className="z-10 max-w-5xl w-full items-center justify-between font-mono">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
